from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class PetsAssets: 


	# Click Rule Assets
	# description 
	C_CLICK_PETS_1 = RuleClick(roi_front=(761,383,17,13), roi_back=(759,382,19,15), name="click_pets_1")
	# description 
	C_CLICK_PETS_2 = RuleClick(roi_front=(846,398,13,18), roi_back=(844,397,15,21), name="click_pets_2")
	# description 
	C_CLICK_PETS_3 = RuleClick(roi_front=(899,403,15,9), roi_back=(898,402,18,11), name="click_pets_3")
	# description 
	C_CLICK_PETS_4 = RuleClick(roi_front=(252,577,15,25), roi_back=(251,576,18,27), name="click_pets_4")
	# description 
	C_CLICK_PETS_5 = RuleClick(roi_front=(401,597,18,18), roi_back=(399,596,21,21), name="click_pets_5")
	# description 
	C_CLICK_PETS_6 = RuleClick(roi_front=(458,551,11,22), roi_back=(456,549,14,25), name="click_pets_6")
	# description 
	C_CLICK_AWARD = RuleClick(roi_front=(692,520,150,62), roi_back=(690,519,152,65), name="click_award")


	# Image Rule Assets
	# 宠物小屋 
	I_PET_HOUSE = RuleImage(roi_front=(1012,414,56,25), roi_back=(672,387,603,180), threshold=0.7, method="Template matching", file="./tasks/Pets/pet/pet_house.png")
	# 爪印 
	I_PET_CLAW = RuleImage(roi_front=(1171,625,55,56), roi_back=(1171,625,55,56), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_claw.png")
	# 其乐融融 
	I_PET_HAPPY = RuleImage(roi_front=(853,614,67,70), roi_back=(853,614,67,70), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_happy.png")
	# 快速喂养 
	I_PET_FEAST = RuleImage(roi_front=(849,624,69,49), roi_back=(849,624,69,49), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_feast.png")
	# 玩耍 
	I_PET_PLAY = RuleImage(roi_front=(788,500,75,75), roi_back=(788,500,75,75), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_play.png")
	# 喂食 
	I_PET_FEED = RuleImage(roi_front=(899,511,79,68), roi_back=(884,485,127,123), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_feed.png")
	# 跳过 
	I_PET_SKIP = RuleImage(roi_front=(1089,119,72,41), roi_back=(999,42,242,147), threshold=0.65, method="Template matching", file="./tasks/Pets/pet/pet_pet_skip.png")
	# 退出 
	I_PET_EXIT = RuleImage(roi_front=(37,24,39,39), roi_back=(7,6,102,81), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_pet_exit.png")
	# description 
	I_PET_TO_YARD = RuleImage(roi_front=(34,628,49,47), roi_back=(7,585,138,118), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_to_yard.png")
	# description 
	I_PET_YARD = RuleImage(roi_front=(17,633,65,77), roi_back=(3,560,144,151), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_yard.png")
	# description 
	I_PET_TO_FEED = RuleImage(roi_front=(807,241,59,67), roi_back=(83,159,997,484), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_to_feed.png")
	# description 
	I_PET_SORT = RuleImage(roi_front=(382,95,54,34), roi_back=(260,85,213,59), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_sort.png")
	# description 
	I_PET_SORT_REVERSE = RuleImage(roi_front=(382,95,54,34), roi_back=(260,85,213,59), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_sort_reverse.png")
	# description 
	I_PET_FIND_FOOD = RuleImage(roi_front=(383,192,46,37), roi_back=(181,148,361,140), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_find_food.png")
	# description 
	I_PET_SELECT_FOOD = RuleImage(roi_front=(383,192,46,37), roi_back=(682,249,356,120), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_select_food.png")
	# description 
	I_PET_ENSURE = RuleImage(roi_front=(799,569,128,37), roi_back=(757,539,219,96), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_ensure.png")
	# description 
	I_PET_AWARD = RuleImage(roi_front=(710,336,32,32), roi_back=(495,253,441,211), threshold=0.8, method="Template matching", file="./tasks/Pets/pet/pet_award.png")
	# description 
	I_PET_FLAG_1 = RuleImage(roi_front=(335,544,63,20), roi_back=(290,502,152,111), threshold=0.7, method="Template matching", file="./tasks/Pets/pet/pet_flag_1.png")
	# description 
	I_PET_FLAG_2 = RuleImage(roi_front=(806,382,61,11), roi_back=(729,341,191,102), threshold=0.7, method="Template matching", file="./tasks/Pets/pet/pet_flag_2.png")


	# Ocr Rule Assets
	# 喂食的体力 
	O_PET_FEED_AP = RuleOcr(roi=(817,538,57,33), area=(817,538,57,33), mode="Digit", method="Default", keyword="", name="pet_feed_ap")
	# 玩耍的体力 
	O_PET_PLAY_GOLD = RuleOcr(roi=(681,524,74,40), area=(681,524,74,40), mode="Digit", method="Default", keyword="", name="pet_play_gold")


