from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ReturnGiftAssets: 


	# Image Rule Assets
	# SR碎片模板sr_1 
	I_SR_1 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_1.png")
	# SR碎片模板sr_2 
	I_SR_2 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_2.png")
	# SR碎片模板sr_3 
	I_SR_3 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_3.png")
	# SR碎片模板sr_4 
	I_SR_4 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_4.png")
	# SR碎片模板sr_5 
	I_SR_5 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_5.png")
	# SR碎片模板sr_6 
	I_SR_6 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_6.png")
	# SR碎片模板sr_7 
	I_SR_7 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_7.png")
	# SR碎片模板sr_8 
	I_SR_8 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_8.png")
	# SR碎片模板sr_9 
	I_SR_9 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_9.png")
	# SR碎片模板sr_10 
	I_SR_10 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_10.png")
	# SR碎片模板sr_11 
	I_SR_11 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_11.png")
	# SR碎片模板sr_12 
	I_SR_12 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_12.png")
	# SR碎片模板sr_13 
	I_SR_13 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_13.png")
	# SR碎片模板sr_14 
	I_SR_14 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_14.png")
	# SR碎片模板sr_15 
	I_SR_15 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_15.png")
	# SR碎片模板sr_16 
	I_SR_16 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_16.png")
	# SR碎片模板sr_17 
	I_SR_17 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_17.png")
	# SR碎片模板sr_18 
	I_SR_18 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_18.png")
	# SR碎片模板sr_19 
	I_SR_19 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_19.png")
	# SR碎片模板sr_20 
	I_SR_20 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_20.png")
	# SR碎片模板sr_21 
	I_SR_21 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_21.png")
	# SR碎片模板sr_22 
	I_SR_22 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_22.png")
	# SR碎片模板sr_23 
	I_SR_23 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_23.png")
	# SR碎片模板sr_24 
	I_SR_24 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_24.png")
	# SR碎片模板sr_25 
	I_SR_25 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_25.png")
	# SR碎片模板sr_26 
	I_SR_26 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_26.png")
	# SR碎片模板sr_27 
	I_SR_27 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_27.png")
	# SR碎片模板sr_28 
	I_SR_28 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_28.png")
	# SR碎片模板sr_29 
	I_SR_29 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_29.png")
	# SR碎片模板sr_30 
	I_SR_30 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_30.png")
	# SR碎片模板sr_31 
	I_SR_31 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_31.png")
	# SR碎片模板sr_32 
	I_SR_32 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_32.png")
	# SR碎片模板sr_33 
	I_SR_33 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_33.png")
	# SR碎片模板sr_34 
	I_SR_34 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_34.png")
	# SR碎片模板sr_35 
	I_SR_35 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_35.png")
	# SR碎片模板sr_36 
	I_SR_36 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_36.png")
	# SR碎片模板sr_37 
	I_SR_37 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_37.png")
	# SR碎片模板sr_38 
	I_SR_38 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_38.png")
	# SR碎片模板sr_39 
	I_SR_39 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_39.png")
	# SR碎片模板sr_40 
	I_SR_40 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_40.png")
	# SR碎片模板sr_41 
	I_SR_41 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_41.png")
	# SR碎片模板sr_42 
	I_SR_42 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_42.png")
	# SR碎片模板sr_43 
	I_SR_43 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_43.png")
	# SR碎片模板sr_44 
	I_SR_44 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_44.png")
	# SR碎片模板sr_45 
	I_SR_45 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_45.png")
	# SR碎片模板sr_46 
	I_SR_46 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_46.png")
	# SR碎片模板sr_47 
	I_SR_47 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_47.png")
	# SR碎片模板sr_48 
	I_SR_48 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_48.png")
	# SR碎片模板sr_49 
	I_SR_49 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_49.png")
	# SR碎片模板sr_50 
	I_SR_50 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_50.png")
	# SR碎片模板sr_51 
	I_SR_51 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_51.png")
	# SR碎片模板sr_52 
	I_SR_52 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_52.png")
	# SR碎片模板sr_53 
	I_SR_53 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_53.png")
	# SR碎片模板sr_54 
	I_SR_54 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_54.png")
	# SR碎片模板sr_55 
	I_SR_55 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_55.png")
	# SR碎片模板sr_56 
	I_SR_56 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_56.png")
	# SR碎片模板sr_57 
	I_SR_57 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_57.png")
	# SR碎片模板sr_58 
	I_SR_58 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_58.png")
	# SR碎片模板sr_59 
	I_SR_59 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_59.png")
	# SR碎片模板sr_60 
	I_SR_60 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_60.png")
	# SR碎片模板sr_61 
	I_SR_61 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_61.png")
	# SR碎片模板sr_62 
	I_SR_62 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_62.png")
	# SR碎片模板sr_63 
	I_SR_63 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_63.png")
	# SR碎片模板sr_64 
	I_SR_64 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_64.png")
	# SR碎片模板sr_65 
	I_SR_65 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_65.png")
	# SR碎片模板sr_66 
	I_SR_66 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_66.png")
	# SR碎片模板sr_67 
	I_SR_67 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_67.png")
	# SR碎片模板sr_68 
	I_SR_68 = RuleImage(roi_front=(0,0,104,146), roi_back=(334,163,612,454), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/sr_68.png")
	# description 
	I_PAGE_PIECE = RuleImage(roi_front=(694,100,43,33), roi_back=(662,82,114,67), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/page_piece.png")
	# description 
	I_TO_PAGE_PIECE = RuleImage(roi_front=(944,597,54,58), roi_back=(913,569,115,116), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/count/to_page_piece.png")


	# Click Rule Assets
	# description 
	C_R_TORECEIVE_FLAG_CLICK = RuleClick(roi_front=(1063,600,47,54), roi_back=(1062,598,50,57), name="r_toreceive_flag_click")
	# description 
	C_R_TORECEIVE_FLAG2_CLICK = RuleClick(roi_front=(979,319,41,70), roi_back=(978,318,43,73), name="r_toreceive_flag2_click")
	# description 
	C_R_AWARD_CLICK = RuleClick(roi_front=(1016,110,89,444), roi_back=(1015,109,91,447), name="r_award_click")
	# description 
	C_R_TOSEND_CLICK = RuleClick(roi_front=(968,632,54,39), roi_back=(967,630,57,42), name="r_tosend_click")


	# Image Rule Assets
	# description 
	I_R_SEND_FLAG = RuleImage(roi_front=(173,606,206,51), roi_back=(153,588,250,87), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/image/r_send_flag.png")
	# description 
	I_R_TORECEIVE_FLAG = RuleImage(roi_front=(1116,584,19,23), roi_back=(1018,561,150,125), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_toreceive_flag.png")
	# description 
	I_R_SEND_BTN = RuleImage(roi_front=(862,175,61,35), roi_back=(794,71,203,507), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_send_btn.png")
	# description 
	I_R_TORECEIVE_FLAG2 = RuleImage(roi_front=(1022,299,19,18), roi_back=(962,258,105,178), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/image/r_toreceive_flag2.png")
	# description 
	I_R_RECEIVE_BTN = RuleImage(roi_front=(922,605,50,50), roi_back=(893,578,118,114), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_receive_btn.png")
	# description 
	I_R_RECEIVE_ENSURE = RuleImage(roi_front=(722,413,70,37), roi_back=(634,359,235,127), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_receive_ensure.png")
	# description 
	I_R_BACK_RED = RuleImage(roi_front=(936,87,38,39), roi_back=(893,65,127,89), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_back_red.png")
	# description 
	I_R_AWARD = RuleImage(roi_front=(476,188,326,83), roi_back=(364,123,558,223), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_award.png")
	# description 
	I_R_PAGE_GUILD = RuleImage(roi_front=(964,632,59,69), roi_back=(895,578,246,139), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_page_guild.png")
	# description 
	I_R_BACK_Y = RuleImage(roi_front=(29,10,41,41), roi_back=(3,3,93,77), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_back_y.png")


	# Ocr Rule Assets
	# 碎片数量 
	O_PIECE_FLAG = RuleOcr(roi=(0,0,100,100), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="piece_flag")


	# Swipe Rule Assets
	# description 
	S_R_FIND_SEND_BTN = RuleSwipe(roi_front=(995,504,114,23), roi_back=(984,75,122,25), mode="default", name="r_find_send_btn")


