from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ReturnGiftAssets: 


	# Click Rule Assets
	# description 
	C_R_TORECEIVE_FLAG_CLICK = RuleClick(roi_front=(1063,600,47,54), roi_back=(1062,598,50,57), name="r_toreceive_flag_click")
	# description 
	C_R_TORECEIVE_FLAG2_CLICK = RuleClick(roi_front=(979,319,41,70), roi_back=(978,318,43,73), name="r_toreceive_flag2_click")
	# description 
	C_R_AWARD_CLICK = RuleClick(roi_front=(1016,110,89,444), roi_back=(1015,109,91,447), name="r_award_click")
	# description 
	C_R_TOSEND_CLICK = RuleClick(roi_front=(968,632,54,39), roi_back=(967,630,57,42), name="r_tosend_click")


	# Image Rule Assets
	# description 
	I_R_SEND_FLAG = RuleImage(roi_front=(173,606,206,51), roi_back=(153,588,250,87), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/image/r_send_flag.png")
	# description 
	I_R_TORECEIVE_FLAG = RuleImage(roi_front=(1116,584,19,23), roi_back=(1018,561,150,125), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_toreceive_flag.png")
	# description 
	I_R_SEND_BTN = RuleImage(roi_front=(862,175,61,35), roi_back=(794,71,203,507), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_send_btn.png")
	# description 
	I_R_TORECEIVE_FLAG2 = RuleImage(roi_front=(1022,299,19,18), roi_back=(962,258,105,178), threshold=0.8, method="Template matching", file="./tasks/ReturnGift/image/r_toreceive_flag2.png")
	# description 
	I_R_RECEIVE_BTN = RuleImage(roi_front=(922,605,50,50), roi_back=(893,578,118,114), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_receive_btn.png")
	# description 
	I_R_RECEIVE_ENSURE = RuleImage(roi_front=(722,413,70,37), roi_back=(634,359,235,127), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_receive_ensure.png")
	# description 
	I_R_BACK_RED = RuleImage(roi_front=(936,87,38,39), roi_back=(893,65,127,89), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_back_red.png")
	# description 
	I_R_AWARD = RuleImage(roi_front=(476,188,326,83), roi_back=(364,123,558,223), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_award.png")
	# description 
	I_R_PAGE_GUILD = RuleImage(roi_front=(964,632,59,69), roi_back=(895,578,246,139), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_page_guild.png")
	# description 
	I_R_BACK_Y = RuleImage(roi_front=(29,10,41,41), roi_back=(3,3,93,77), threshold=0.7, method="Template matching", file="./tasks/ReturnGift/image/r_back_y.png")


	# Ocr Rule Assets
	# 碎片数量 
	O_PIECE_FLAG = RuleOcr(roi=(0,0,100,100), area=(0,0,100,100), mode="DigitCounter", method="Default", keyword="", name="piece_flag")


	# Swipe Rule Assets
	# description 
	S_R_FIND_SEND_BTN = RuleSwipe(roi_front=(995,504,114,23), roi_back=(984,75,122,25), mode="default", name="r_find_send_btn")


