from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SougenbiAssets: 


	# Click Rule Assets
	# description 
	C_C_GREED = RuleClick(roi_front=(129,104,85,42), roi_back=(128,103,88,44), name="c_greed")
	# description 
	C_C_ANGER = RuleClick(roi_front=(133,214,80,33), roi_back=(132,212,83,35), name="c_anger")
	# description 
	C_C_FOOLERY = RuleClick(roi_front=(134,318,83,31), roi_back=(133,317,85,34), name="c_foolery")


	# Image Rule Assets
	# 进入业原火 
	I_S_SOUGENBI = RuleImage(roi_front=(539,95,80,190), roi_back=(418,51,232,388), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_sougenbi.png")
	# 贪 
	I_S_GREED = RuleImage(roi_front=(133,113,84,31), roi_back=(84,92,191,87), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_greed.png")
	#  
	I_S_ANGER = RuleImage(roi_front=(133,216,84,30), roi_back=(87,198,167,68), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_anger.png")
	# 痴 
	I_S_FOOLERY = RuleImage(roi_front=(133,319,84,30), roi_back=(91,307,147,63), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_foolery.png")
	# description 
	I_S_TEAM_LOCK = RuleImage(roi_front=(701,653,26,31), roi_back=(669,638,153,70), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_team_lock.png")
	# description 
	I_S_TEAM_UNLOCK = RuleImage(roi_front=(376,140,59,54), roi_back=(671,647,225,63), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_team_unlock.png")
	# 挑战 
	I_S_FIRE = RuleImage(roi_front=(1055,605,85,34), roi_back=(1013,568,157,133), threshold=0.7, method="Template matching", file="./tasks/Sougenbi/s/s_fire.png")
	# 确认进入业原火 
	I_S_CHECK_SOUGENBI = RuleImage(roi_front=(937,100,174,77), roi_back=(858,73,398,137), threshold=0.8, method="Template matching", file="./tasks/Sougenbi/s/s_check_sougenbi.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_S_GREED = RuleOcr(roi=(597,13,67,31), area=(595,11,70,34), mode="Single", method="Default", keyword="", name="s_greed")
	# Ocr-description 
	O_S_ANGER = RuleOcr(roi=(771,14,76,31), area=(770,13,79,34), mode="Digit", method="Default", keyword="", name="s_anger")
	# Ocr-description 
	O_S_FOOLERY = RuleOcr(roi=(951,17,68,27), area=(949,15,71,30), mode="Digit", method="Default", keyword="", name="s_foolery")


