from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MasterDiscipleAssets: 


	# Image Rule Assets
	# description 
	I_TO_TASK = RuleImage(roi_front=(272,301,26,153), roi_back=(173,215,268,377), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/to_task.png")
	# description 
	I_TO_BATTLE_GUARD = RuleImage(roi_front=(1152,339,54,26), roi_back=(784,322,439,60), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/to_battle_guard.png")
	# description 
	I_PAGE_TASK = RuleImage(roi_front=(883,26,97,38), roi_back=(775,18,383,80), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/page_task.png")
	# description 
	I_PAGE_BATTLE_GUARD = RuleImage(roi_front=(166,19,122,39), roi_back=(117,9,241,92), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/page_battle_guard.png")
	# description 
	I_TO_TEAM = RuleImage(roi_front=(1005,190,167,58), roi_back=(870,163,360,190), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/to_team.png")
	# description 
	I_PAGE_TEAM = RuleImage(roi_front=(93,27,128,36), roi_back=(64,10,211,87), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/page_team.png")
	# description 
	I_CLICK_INVITE_ADD = RuleImage(roi_front=(1143,253,55,54), roi_back=(0,0,1280,720), threshold=0.85, method="Template matching", file="./tasks/MasterDisciple/res/click_invite_add.png")
	# description 
	I_SWITCH_ALL = RuleImage(roi_front=(507,294,39,46), roi_back=(466,268,344,87), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/switch_all.png")
	# description 
	I_ENSURE_SWITCH = RuleImage(roi_front=(607,495,65,42), roi_back=(466,475,333,91), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/ensure_switch.png")
	# description 
	I_SWITCH_ALL_OVER = RuleImage(roi_front=(507,294,39,46), roi_back=(466,268,344,87), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/switch_all_over.png")
	# description 
	I_TO_SWITCH = RuleImage(roi_front=(826,641,30,33), roi_back=(556,616,430,79), threshold=0.8, method="Template matching", file="./tasks/MasterDisciple/res/to_switch.png")
	# description 
	I_ACCEPT = RuleImage(roi_front=(116,229,53,47), roi_back=(0,205,290,374), threshold=0.7, method="Template matching", file="./tasks/MasterDisciple/res/accept.png")


	# Ocr Rule Assets
	# description 
	O_FLAG_TASK_GUARD = RuleOcr(roi=(799,183,253,505), area=(797,182,256,508), mode="full", method="Default", keyword="守护历练", name="flag_task_guard")
	# description 
	O_FIND_SHIKIGAMI_HELP = RuleOcr(roi=(228,605,874,87), area=(0,0,100,100), mode="Full", method="Default", keyword="15", name="find_shikigami_help")
	# description 
	O_ACCEPT_NAME = RuleOcr(roi=(115,256,300,47), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="accept_name")
	# description 
	O_ADD_ALL = RuleOcr(roi=(609,640,167,35), area=(0,0,100,100), mode="Single", method="Default", keyword="所有人", name="add_all")


	# Swipe Rule Assets
	# description 
	S_TO_BATTLE_SWIPE = RuleSwipe(roi_front=(916,614,47,11), roi_back=(67,324,36,157), mode="default", name="to_battle_swipe")
	# description 
	S_FIND_TASK_GUARD = RuleSwipe(roi_front=(910,614,54,13), roi_back=(911,450,59,13), mode="default", name="find_task_guard")


