from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SearchIdAssets: 


	# Click Rule Assets
	# description 
	C_CLICK_INPUT = RuleClick(roi_front=(484,127,394,25), roi_back=(483,126,397,27), name="click_input")
	# description 
	C_CLICK_SERVER = RuleClick(roi_front=(195,119,91,31), roi_back=(193,118,94,34), name="click_server")
	# description 
	C_CLICK_CHARACTER = RuleClick(roi_front=(176,261,43,42), roi_back=(175,260,46,45), name="click_character")
	# description 
	C_CLICK_SPACE_EXIT = RuleClick(roi_front=(1161,99,35,33), roi_back=(1159,98,38,35), name="click_space_exit")


	# Image Rule Assets
	# description 
	I_SEARCH_ENSURE = RuleImage(roi_front=(1053,25,63,34), roi_back=(1005,5,147,86), threshold=0.7, method="Template matching", file="./tasks/SearchId/res/search_ensure.png")
	# description 
	I_SERVER_ALL = RuleImage(roi_front=(212,120,57,29), roi_back=(195,111,98,50), threshold=0.7, method="Template matching", file="./tasks/SearchId/res/server_all.png")
	# description 
	I_SERVER_ALL_SELECT = RuleImage(roi_front=(185,159,55,37), roi_back=(164,150,106,54), threshold=0.7, method="Template matching", file="./tasks/SearchId/res/server_all_select.png")
	# description 
	I_SEARCH_FLAG = RuleImage(roi_front=(1037,119,57,33), roi_back=(1002,106,124,53), threshold=0.7, method="Template matching", file="./tasks/SearchId/res/search_flag.png")
	# description 
	I_TO_SEARCH = RuleImage(roi_front=(1208,297,34,69), roi_back=(1179,265,91,132), threshold=0.8, method="Template matching", file="./tasks/SearchId/res/to_search.png")
	# description 
	I_SEARCH_RESULT = RuleImage(roi_front=(183,185,100,33), roi_back=(138,167,187,58), threshold=0.8, method="Template matching", file="./tasks/SearchId/res/search_result.png")
	# description 
	I_TO_SPACE = RuleImage(roi_front=(502,290,120,41), roi_back=(124,54,589,596), threshold=0.8, method="Template matching", file="./tasks/SearchId/res/to_space.png")
	# description 
	I_PAGE_SPACE = RuleImage(roi_front=(151,503,46,42), roi_back=(62,41,1153,656), threshold=0.8, method="Template matching", file="./tasks/SearchId/res/page_space.png")


	# Ocr Rule Assets
	# description 
	O_LEVEL = RuleOcr(roi=(163,247,34,31), area=(191,273,25,31), mode="Digit", method="Default", keyword="", name="level")


