from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeThemeAssets: 


	# Image Rule Assets
	# 拾光永恒关 
	I_THEME_1_SCROLL_CLOSE = RuleImage(roi_front=(1185,637,44,72), roi_back=(1129,604,151,116), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeTheme/theme1/theme1_theme_1_scroll_close.png")
	# 拾光永恒开 
	I_THEME_1_SCROLL_OPEN = RuleImage(roi_front=(1189,627,44,72), roi_back=(1129,604,151,116), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeTheme/theme1/theme1_theme_1_scroll_open.png")


	# Image Rule Assets
	# 新语明霄关 
	I_THEME_2_SCROLL_CLOSE = RuleImage(roi_front=(1188,626,44,72), roi_back=(1129,604,151,116), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeTheme/theme2/theme2_theme_2_scroll_close.png")
	# 新语明霄开 
	I_THEME_2_SCROLL_OPEN = RuleImage(roi_front=(1201,620,44,72), roi_back=(1129,604,151,116), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeTheme/theme2/theme2_theme_2_scroll_open.png")


