from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets: 


	# Ocr Rule Assets
	# AP20挑战按钮OCR 
	O_FIRE_AP20 = RuleOcr(roi=(1137,587,90,50), area=(1162,603,37,21), mode="Single", method="Default", keyword="挑战", name="fire_ap20")
	# AP20剩余攻击次数(格式: X/20) 
	O_REMAIN_AP20 = RuleOcr(roi=(1109,670,151,30), area=(0,0,0,0), mode="DigitCounter", method="Default", keyword="", name="remain_ap20")


	# Image Rule Assets
	# 从活动主页面进入AP20 
	I_TO_AP20 = RuleImage(roi_front=(856,261,31,119), roi_back=(743,95,236,430), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/to_ap20.png")
	# 确认进入AP20入口列表页面 
	I_CHECK_AP20 = RuleImage(roi_front=(447,99,35,35), roi_back=(358,63,199,176), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/check_ap20.png")
	# 确认进入AP20 BOSS战斗页面 
	I_CHECK_AP20_BOSS = RuleImage(roi_front=(1137,585,90,50), roi_back=(1012,514,267,191), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/check_ap20_boss.png")
	# AP20入口列表中点击进入BOSS 
	I_TO_AP20_BOSS = RuleImage(roi_front=(1157,318,41,47), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/to_ap20_boss.png")
	# AP20入口0 
	I_AP20_ENTRY_0 = RuleImage(roi_front=(828,434,33,47), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_0.png")
	# AP20入口1 
	I_AP20_ENTRY_1 = RuleImage(roi_front=(840,449,41,42), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_1.png")
	# AP20入口2 
	I_AP20_ENTRY_2 = RuleImage(roi_front=(913,519,39,46), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_2.png")
	# AP20入口3 
	I_AP20_ENTRY_3 = RuleImage(roi_front=(850,398,42,47), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_3.png")
	# AP20入口4 
	I_AP20_ENTRY_4 = RuleImage(roi_front=(924,514,46,47), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_4.png")
	# AP20入口5 
	I_AP20_ENTRY_5 = RuleImage(roi_front=(949,450,42,47), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_5.png")
	# AP20入口6 
	I_AP20_ENTRY_6 = RuleImage(roi_front=(971,483,46,49), roi_back=(212,61,1060,619), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/ap20/ap20_entry_6.png")


	# Swipe Rule Assets
	# AP20入口列表向左滑动 
	S_AP20_SWIPE_LEFT = RuleSwipe(roi_front=(917,308,49,25), roi_back=(1174,310,47,21), mode="Default", name="ap20_swipe_left")


	# Click Rule Assets
	# description 
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# description 
	C_RANDOM_RIGHT = RuleClick(roi_front=(1218,468,43,73), roi_back=(1216,467,46,76), name="random_right")
	# description 
	C_RANDOM_TOP = RuleClick(roi_front=(466,11,214,46), roi_back=(465,10,216,48), name="random_top")
	# description 
	C_RANDOM_BOTTOM = RuleClick(roi_front=(389,665,277,36), roi_back=(388,664,280,39), name="random_bottom")
	# description 
	C_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="random_all")


	# Image Rule Assets
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(825,657,28,25), roi_back=(739,613,276,85), threshold=0.5, method="Template matching", file="./tasks/ActivityShikigami/as/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(884,648,28,25), roi_back=(733,607,266,95), threshold=0.5, method="Template matching", file="./tasks/ActivityShikigami/as/as_unlock.png")
	# 活动爬塔标志 
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1139,544,26,27), roi_back=(1117,500,63,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb_mode_pass.png")
	# 体力爬塔标志 
	I_CLIMB_MODE_AP = RuleImage(roi_front=(1090,541,29,27), roi_back=(1062,516,200,193), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb_mode_ap.png")
	# 切换按键 
	I_CLIMB_MODE_SWITCH = RuleImage(roi_front=(1235,549,25,21), roi_back=(1222,531,50,63), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/climb_mode_switch.png")
	# 未开启五倍 
	I_OFF_X5 = RuleImage(roi_front=(870,656,25,21), roi_back=(839,637,94,64), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_off_x5.png")
	# 开启五倍 
	I_ON_X5 = RuleImage(roi_front=(870,656,25,21), roi_back=(839,637,94,64), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_on_x5.png")


	# Image Rule Assets
	# 进入活动 
	I_SHI = RuleImage(roi_front=(1182,224,42,31), roi_back=(1163,135,83,393), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/shi.png")
	# 左上角返回 
	I_BACK_GREEN = RuleImage(roi_front=(27,19,34,38), roi_back=(2,1,170,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_back_green.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_skip_button.png")
	# 红色退出 
	I_RED_EXIT = RuleImage(roi_front=(1162,96,39,38), roi_back=(1029,53,216,159), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_red_exit.png")
	# 进入主要的战斗界面 
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(1042,186,39,127), roi_back=(976,96,195,326), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/to_battle_main.png")
	# 点击进入boss战斗页面 
	I_TO_BATTLE_BOSS = RuleImage(roi_front=(937,249,34,122), roi_back=(878,153,161,284), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/to_battle_boss.png")
	# description 
	I_CHECK_BATTLE_MAIN = RuleImage(roi_front=(148,17,135,39), roi_back=(78,5,260,107), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/check_battle_main.png")
	# description 
	I_CHECK_BATTLE_BOSS = RuleImage(roi_front=(151,17,126,42), roi_back=(118,5,184,80), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/check_battle_boss.png")
	# 从main进入到式神录 
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1018,561,37,45), roi_back=(976,539,146,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/battle_main_to_records.png")


	# Image Rule Assets
	# description 
	I_PASS_1 = RuleImage(roi_front=(359,295,100,53), roi_back=(68,203,1138,369), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_1.png")
	# description 
	I_PASS_2 = RuleImage(roi_front=(645,224,92,57), roi_back=(98,205,1076,366), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_2.png")
	# description 
	I_PASS_3 = RuleImage(roi_front=(648,227,91,55), roi_back=(103,162,1077,416), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_3.png")
	# description 
	I_PASS_4 = RuleImage(roi_front=(586,424,100,58), roi_back=(99,194,1080,398), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_4.png")
	# 箱子 
	I_PASS_5 = RuleImage(roi_front=(946,415,65,48), roi_back=(97,194,1036,398), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_5.png")
	# 印记 
	I_PASS_6 = RuleImage(roi_front=(668,221,54,50), roi_back=(107,159,1012,394), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_6.png")
	# description 
	I_PASS_7 = RuleImage(roi_front=(329,233,51,51), roi_back=(95,180,1056,394), threshold=0.65, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_7.png")
	# 印记选中间的 
	I_PASS_8 = RuleImage(roi_front=(579,276,100,100), roi_back=(577,296,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_8.png")
	# description 
	I_PASS_9 = RuleImage(roi_front=(558,643,160,44), roi_back=(480,601,306,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_9.png")
	# 印记选左边的 
	I_PASS_10 = RuleImage(roi_front=(279,309,100,100), roi_back=(291,305,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_10.png")
	# 印记选右边的 
	I_PASS_11 = RuleImage(roi_front=(918,304,100,100), roi_back=(914,308,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_11.png")
	# 击败魇兽将直接前往下一层 
	I_PASS12 = RuleImage(roi_front=(870,356,100,50), roi_back=(104,169,1109,425), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass12.png")
	# 魇兽将的战斗图片 
	I_PASS_13 = RuleImage(roi_front=(1018,570,100,100), roi_back=(984,538,169,152), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_13.png")


	# Ocr Rule Assets
	# 挑战 
	O_FIRE = RuleOcr(roi=(1133,605,83,41), area=(1165,609,31,26), mode="Single", method="Default", keyword="挑战", name="fire")
	# 体力的数量检测 
	O_REMAIN_AP = RuleOcr(roi=(774,16,71,31), area=(773,16,70,34), mode="DigitCounter", method="Default", keyword="", name="remain_ap")
	# 活动体力的剩余检测 
	O_REMAIN_PASS = RuleOcr(roi=(593,14,57,35), area=(586,17,66,30), mode="DigitCounter", method="Default", keyword="", name="remain_pass")
	# 还有多少次购买体力的机会 
	O_REMAIN_BUY = RuleOcr(roi=(808,531,39,42), area=(808,531,39,42), mode="DigitCounter", method="Default", keyword="", name="remain_buy")
	# 活动票数（没有百分比） 
	O_REMAIN_PASS2 = RuleOcr(roi=(750,17,88,29), area=(750,17,88,29), mode="Digit", method="Default", keyword="", name="remain_pass2")
	# boss剩余攻击次数 
	O_REMAIN_BOSS = RuleOcr(roi=(1097,668,166,34), area=(1080,656,192,56), mode="DigitCounter", method="Default", keyword="", name="remain_boss")
	# 100体活动门票检测 
	O_REMAIN_AP100 = RuleOcr(roi=(922,21,112,39), area=(913,8,131,62), mode="Digit", method="Default", keyword="", name="remain_ap100")
	# 进入100体活动标识 
	O_ENTER_AP100 = RuleOcr(roi=(73,98,95,32), area=(5,79,256,108), mode="Single", method="Default", keyword="将魂试炼", name="enter_ap100")
	# description 
	O_FIRE2 = RuleOcr(roi=(1142,589,96,50), area=(1167,601,35,27), mode="Single", method="Default", keyword="挑战", name="fire2")
	# 五倍券数量 
	O_REMAIN_X5 = RuleOcr(roi=(936,14,104,34), area=(935,10,107,44), mode="DigitCounter", method="Default", keyword="", name="remain_x5")


	# Click Rule Assets
	# 大富翁骰子1点击区域 
	C_MONOPOLY_DICE_1_CLICK = RuleClick(roi_front=(356,284,59,85), roi_back=(354,282,62,87), name="monopoly_dice_1_click")
	# 大富翁骰子2点击区域 
	C_MONOPOLY_DICE_2_CLICK = RuleClick(roi_front=(599,268,73,90), roi_back=(597,267,75,92), name="monopoly_dice_2_click")
	# 大富翁骰子3点击区域 
	C_MONOPOLY_DICE_3_CLICK = RuleClick(roi_front=(827,280,58,69), roi_back=(826,278,61,71), name="monopoly_dice_3_click")
	# 大富翁问答场景答案1点击位置 
	C_MONOPOLY_QA_ANSWER_1 = RuleClick(roi_front=(593,294,134,39), roi_back=(592,293,136,42), name="monopoly_qa_answer_1")


	# Image Rule Assets
	# 进入大富翁战斗主页面 
	I_TO_MONOPOLY_MAIN = RuleImage(roi_front=(664,360,29,132), roi_back=(645,325,85,212), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/to_monopoly_main.png")
	# 确认在大富翁主页面 
	I_CHECK_MONOPOLY_MAIN = RuleImage(roi_front=(843,581,31,34), roi_back=(815,567,69,59), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/check_monopoly_main.png")
	# 大富翁问答页面标识 
	I_MONOPOLY_PAGE_QA = RuleImage(roi_front=(532,89,236,70), roi_back=(498,78,305,91), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_qa.png")
	# 大富翁商店页面标识 
	I_MONOPOLY_PAGE_SHOP = RuleImage(roi_front=(512,67,257,71), roi_back=(421,38,414,140), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_shop.png")
	# 大富翁战斗触发火图标 
	I_MONOPOLY_PAGE_FIRE = RuleImage(roi_front=(987,573,78,38), roi_back=(977,564,95,57), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_fire.png")
	# 大富翁骰子模式战斗触发火图标 
	I_MONOPOLY_PAGE_FIRE_DICE = RuleImage(roi_front=(990,564,69,59), roi_back=(963,530,119,112), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_fire_dice.png")
	# 大富翁投掷骰子页面标识 
	I_MONOPOLY_PAGE_ROLL = RuleImage(roi_front=(1061,555,90,35), roi_back=(990,512,212,126), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_roll.png")
	# 大富翁选择骰子页面标识 
	I_MONOPOLY_PAGE_SELECT_DICE = RuleImage(roi_front=(761,201,38,30), roi_back=(401,171,492,73), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_page_select_dice.png")
	# 大富翁骰子1图标 
	I_MONOPOLY_DICE_1_ICON = RuleImage(roi_front=(956,579,30,37), roi_back=(941,568,126,58), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_dice_1_icon.png")
	# 大富翁骰子2图标 
	I_MONOPOLY_DICE_2_ICON = RuleImage(roi_front=(956,579,30,37), roi_back=(941,568,126,58), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_dice_2_icon.png")
	# 大富翁骰子3图标 
	I_MONOPOLY_DICE_3_ICON = RuleImage(roi_front=(956,579,30,37), roi_back=(941,568,126,58), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_dice_3_icon.png")
	# 大富翁普通模式火按钮 
	I_MONOPOLY_FIRE_BTN_NORMAL = RuleImage(roi_front=(1143,592,61,90), roi_back=(1135,579,110,118), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_fire_btn_normal.png")
	# 大富翁骰子模式火按钮 
	I_MONOPOLY_FIRE_BTN_DICE = RuleImage(roi_front=(1143,592,61,90), roi_back=(1135,579,110,118), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_fire_btn_dice.png")
	# 大富翁火按钮切换器 
	I_MONOPOLY_FIRE_SWITCH = RuleImage(roi_front=(1238,543,19,29), roi_back=(1218,528,49,57), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_fire_switch.png")
	# 大富翁商店购买按钮 
	I_MONOPOLY_BUY_BTN = RuleImage(roi_front=(876,471,90,43), roi_back=(828,441,176,95), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_buy_btn.png")
	# 大富翁商店可购买标识 
	I_MONOPOLY_BUY_ENABLE = RuleImage(roi_front=(844,564,26,25), roi_back=(245,536,791,79), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/pass_monopoly/monopoly_buy_enable.png")


	# Ocr Rule Assets
	# 大富翁剩余次数 OCR 
	O_MONOPOLY_REMAIN_PASS = RuleOcr(roi=(1167,19,54,29), area=(1141,11,86,38), mode="DigitCounter", method="Default", keyword="", name="monopoly_remain_pass")


