from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EternitySeaAssets: 


	# Image Rule Assets
	# 选择永生之海 
	I_ETERNITY_SEA = RuleImage(roi_front=(1171,83,56,244), roi_back=(1062,59,191,276), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/eternity_sea.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(967,605,84,48), roi_back=(919,550,162,154), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/form_team.png")
	# 挑战 
	I_ETERNITY_SEA_FIRE = RuleImage(roi_front=(1145,599,88,38), roi_back=(1124,562,142,142), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/eternity_sea_fire.png")
	# 开锁 
	I_ETERNITYSEA_UNLOCK = RuleImage(roi_front=(700,656,31,29), roi_back=(657,636,244,76), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/eternitysea_unlock.png")
	# 关锁 
	I_NEWETERNITYSEA_LOCK = RuleImage(roi_front=(698,655,30,30), roi_back=(668,643,229,70), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/neweternitysea_lock.png")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_pet_present.png")
	# description 
	I_BACK_BOTTOM = RuleImage(roi_front=(1126,49,46,45), roi_back=(1126,49,46,45), threshold=0.8, method="Template matching", file="./tasks/EternitySea/res/res_back_bottom.png")


	# List Rule Assets
	# 永生之海层数列表 
	L_LAYER_LIST = RuleList(folder="./tasks/EternitySea/res", direction="vertical", mode="ocr", roi_back=(129,104,79,574), size=(31, 103), 
					 array=["壹", "贰", "叁", "肆"])


