from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SwitchHelpShikigamiAssets: 


	# Click Rule Assets
	# 准备界面「更换」按钮，点开助战列表 
	C_CLICK_CHANGE = RuleClick(roi_front=(308,452,75,75), roi_back=(306,451,78,78), name="click_change")
	# 好友页「协战」页签点击位 
	C_FRIEND_HELP_CLICK = RuleClick(roi_front=(1204,540,38,70), roi_back=(1203,539,41,73), name="friend_help_click")


	# Image Rule Assets
	# 助战列表未展开时的「更换」旗标 
	I_FLAG_CHANGE = RuleImage(roi_front=(42,646,57,33), roi_back=(11,449,174,253), threshold=0.7, method="Template matching", file="./tasks/Component/SwitchHelpShikigami/res/flag_change.png")
	# 援助式神已上场标记（roi_back 由 OCR 锚点动态改写） 
	I_FLAG_ON_FIELD = RuleImage(roi_front=(650,515,26,23), roi_back=(628,488,79,154), threshold=0.7, method="Template matching", file="./tasks/Component/SwitchHelpShikigami/res/flag_on_field.png")
	# 好友页「协战」页签 
	I_FRIEND_HELP = RuleImage(roi_front=(1205,541,38,71), roi_back=(1187,512,71,118), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchHelpShikigami/res/friend_help.png")
	# 好友协战次数页标题（进入该页的判据） 
	I_FRIEND_HELP_FLAG = RuleImage(roi_front=(803,107,167,34), roi_back=(782,93,210,63), threshold=0.8, method="Template matching", file="./tasks/Component/SwitchHelpShikigami/res/friend_help_flag.png")


	# Ocr Rule Assets
	# 助战列表区域，OCR 定位援助式神卡的 N/15 协战次数标签 
	O_FIND_SHIKIGAMI_HELP = RuleOcr(roi=(228,605,874,87), area=(0,0,100,100), mode="Full", method="Default", keyword="15", name="find_shikigami_help")


	# Swipe Rule Assets
	# 把援助式神拖入出战位（roi_front 由 OCR 锚点动态改写） 
	S_SWIPE_SHIKIGAMI = RuleSwipe(roi_front=(302,589,39,62), roi_back=(623,306,42,107), mode="default", name="swipe_shikigami")


