from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class RealmRaidAssets: 


	# Image Rule Assets
	# 点击结界突破的图片 
	I_REALM_RAID = RuleImage(roi_front=(261,638,44,40), roi_back=(246,628,63,64), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/realm_raid.png")
	# 右上角红色的关闭 
	I_BACK_RED = RuleImage(roi_front=(1178,101,57,64), roi_back=(1178,101,57,64), threshold=0.7, method="Template matching", file="./tasks/RealmRaid/res/res_back_red.png")
	# 没有锁的状态图标 
	I_UNLOCK = RuleImage(roi_front=(821,581,22,38), roi_back=(809,564,51,72), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/unlock.png")
	# 以锁的状态图片 
	I_LOCK = RuleImage(roi_front=(820,581,27,38), roi_back=(808,572,60,77), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/lock.png")
	# 刷新按钮 
	I_FRESH = RuleImage(roi_front=(1006,581,80,36), roi_back=(957,564,182,66), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_fresh.png")
	# 进攻 
	I_FIRE = RuleImage(roi_front=(982,494,136,63), roi_back=(140,129,1024,584), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_fire.png")
	# 打完个后出现的领取奖励 
	I_SOUL_RAID = RuleImage(roi_front=(577,502,100,100), roi_back=(577,502,100,100), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_soul_raid.png")
	# 刷新确认 
	I_FRESH_ENSURE = RuleImage(roi_front=(672,403,173,59), roi_back=(672,403,173,59), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_fresh_ensure.png")
	# 勋章 
	I_MEDAL = RuleImage(roi_front=(907,221,31,31), roi_back=(131,130,1021,437), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_medal.png")
	# 空勋章 
	I_NO_MEDAL = RuleImage(roi_front=(1024,211,33,47), roi_back=(131,130,1021,437), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_no_medal.png")
	# 攻破的标志 
	I_FINISH_SIGN = RuleImage(roi_front=(406,168,48,52), roi_back=(147,136,995,408), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_finish_sign.png")
	# 失败的标志 
	I_FAILURE_SIGN = RuleImage(roi_front=(1057,146,76,48), roi_back=(137,136,1006,415), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_failure_sign.png")


	# Image Rule Assets
	# 已经进攻三次了 
	I_RR_THREE = RuleImage(roi_front=(346,584,42,44), roi_back=(346,584,42,44), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_rr_three.png")
	# 个人 
	I_RR_PERSON = RuleImage(roi_front=(1203,236,56,100), roi_back=(1203,236,56,155), threshold=0.8, method="Template matching", file="./tasks/RealmRaid/res/res_rr_person.png")


	# Ocr Rule Assets
	# 右上角 突破卷的数量 
	O_NUMBER = RuleOcr(roi=(1143,13,80,39), area=(0,0,100,100), mode="DigitCounter", method="Default", keyword="", name="number")
	# text 
	O_TEXT = RuleOcr(roi=(1143,13,80,39), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="text")


