from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GoryouRealmAssets: 


	# Click Rule Assets
	# description 
	C_GR_C_1 = RuleClick(roi_front=(136,105,165,351), roi_back=(134,104,167,354), name="gr_c_1")
	# description 
	C_GR_C_2 = RuleClick(roi_front=(443,116,157,294), roi_back=(442,114,159,297), name="gr_c_2")
	# description 
	C_GR_C_3 = RuleClick(roi_front=(742,128,157,342), roi_back=(741,126,159,344), name="gr_c_3")
	# description 
	C_GR_C_4 = RuleClick(roi_front=(1027,118,186,295), roi_back=(1026,117,188,298), name="gr_c_4")


	# Image Rule Assets
	# 点击挑战 
	I_GR_FIRE = RuleImage(roi_front=(1060,601,73,34), roi_back=(1018,561,174,136), threshold=0.8, method="Template matching", file="./tasks/GoryouRealm/gr/gr_fire.png")
	# description 
	I_GR_LOCK = RuleImage(roi_front=(697,655,34,33), roi_back=(657,646,245,70), threshold=0.8, method="Template matching", file="./tasks/GoryouRealm/gr/gr_lock.png")
	# description 
	I_GR_UNLOCK = RuleImage(roi_front=(700,653,26,31), roi_back=(671,642,207,70), threshold=0.8, method="Template matching", file="./tasks/GoryouRealm/gr/gr_unlock.png")


	# Ocr Rule Assets
	# 多少张票 
	O_GR_TICKET = RuleOcr(roi=(952,15,68,30), area=(951,14,71,33), mode="Digit", method="Default", keyword="", name="gr_ticket")


