from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DailyForFlagAssets: 


	# Click Rule Assets
	# description 
	C_BACK_RED = RuleClick(roi_front=(838,134,57,49), roi_back=(837,133,60,50), name="back_red")


	# Image Rule Assets
	# description 
	I_QIYUAN = RuleImage(roi_front=(966,630,67,61), roi_back=(949,607,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_qiyuan.png")
	# description 
	I_BTN_THINK = RuleImage(roi_front=(928,613,38,35), roi_back=(916,596,70,70), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_btn_think.png")
	# description 
	I_H_BACK_RED = RuleImage(roi_front=(851,144,31,33), roi_back=(777,114,182,110), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_h_back_red.png")
	# description 
	I_BTN_ENSURE = RuleImage(roi_front=(693,405,134,49), roi_back=(639,376,244,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_btn_ensure.png")
	# description 
	I_TO_THINK = RuleImage(roi_front=(1060,602,58,53), roi_back=(1042,580,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_to_think.png")
	# description 
	I_FLAG_THINK = RuleImage(roi_front=(969,176,64,106), roi_back=(938,147,133,158), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_flag_think.png")
	# description 
	I_H_BACK_RED2 = RuleImage(roi_front=(933,88,44,39), roi_back=(906,55,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_h_back_red2.png")


	# Image Rule Assets
	# description 
	I_DONATE = RuleImage(roi_front=(270,494,27,26), roi_back=(243,465,80,87), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_donate.png")
	# description 
	I_ADD = RuleImage(roi_front=(780,276,60,55), roi_back=(763,251,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_add.png")
	# description 
	I_LIMIT = RuleImage(roi_front=(826,349,47,77), roi_back=(817,342,69,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_limit.png")
	# description 
	I_CLICK_DONATE = RuleImage(roi_front=(577,524,133,48), roi_back=(553,501,178,92), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_click_donate.png")
	# description 
	I_AWARD = RuleImage(roi_front=(476,178,327,100), roi_back=(438,160,399,133), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_award.png")


	# Image Rule Assets
	# description 
	I_M_PICTURE = RuleImage(roi_front=(294,10,658,74), roi_back=(292,9,661,77), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/m_picture.png")


	# Image Rule Assets
	# 邮件 
	I_M_MAIN_TO_MAIL = RuleImage(roi_front=(1135,31,41,31), roi_back=(1114,3,82,89), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_main_to_mail.png")
	# 领取邮件 
	I_M_GET_MAIL = RuleImage(roi_front=(65,575,87,66), roi_back=(61,563,98,92), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_get_mail.png")
	# description 
	I_M_PAGE_GET = RuleImage(roi_front=(554,48,195,51), roi_back=(539,33,225,88), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_page_get.png")
	# description 
	I_M_ENSURE_GET = RuleImage(roi_front=(737,553,76,40), roi_back=(698,550,151,52), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_ensure_get.png")
	# 奖励 
	I_M_AWARD = RuleImage(roi_front=(478,131,325,100), roi_back=(427,125,416,114), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_award.png")
	# description 
	I_M_BACK_RED = RuleImage(roi_front=(1152,91,49,47), roi_back=(1131,74,91,82), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_back_red.png")
	# description 
	I_M_PAGE_MAIL = RuleImage(roi_front=(609,54,70,47), roi_back=(585,38,115,89), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_page_mail.png")
	# description 
	I_M_PICTURE = RuleImage(roi_front=(507,51,260,66), roi_back=(449,22,388,101), threshold=0.7, method="Template matching", file="./tasks/DailyForFlag/mail/m_picture.png")
	# description 
	I_M_PICTURE_REFUSE = RuleImage(roi_front=(469,408,109,43), roi_back=(412,375,224,105), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/m_picture_refuse.png")
	# description 
	I_M_FRAME_BACK_RED = RuleImage(roi_front=(1196,31,53,49), roi_back=(1165,13,102,86), threshold=0.7, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_back_red.png")


	# Click Rule Assets
	# description 
	C_MS_REFRESH_ACTION = RuleClick(roi_front=(1202,534,55,52), roi_back=(1202,534,55,52), name="ms_refresh_action")


	# Image Rule Assets
	# description 
	I_MS_REFRESH = RuleImage(roi_front=(1172,589,103,31), roi_back=(1135,501,144,135), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_refresh.png")
	# description 
	I_MS_FLAG = RuleImage(roi_front=(1209,384,60,84), roi_back=(1179,354,100,152), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_flag.png")
	# description 
	I_MS_ENSURE = RuleImage(roi_front=(718,408,81,43), roi_back=(684,404,155,56), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_ensure.png")
	# description 
	I_MS_GOLD = RuleImage(roi_front=(194,254,44,41), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_JADE = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_SHEPI = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_HEISUI = RuleImage(roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_ALL_SHEPI = RuleImage(roi_front=(1,65,100,100), roi_back=(139,107,887,454), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_ALL_FMPI = RuleImage(roi_front=(1,65,100,100), roi_back=(139,107,887,454), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_ALL_HEISUI = RuleImage(roi_front=(1,65,100,100), roi_back=(139,107,887,454), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_SHEPI_1 = RuleImage(roi_front=(1,1,100,100), roi_back=(156,66,198,187), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_2 = RuleImage(roi_front=(1,52,100,100), roi_back=(362,71,218,183), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_3 = RuleImage(roi_front=(7,82,100,100), roi_back=(587,83,224,171), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_4 = RuleImage(roi_front=(5,104,100,100), roi_back=(806,81,214,173), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_5 = RuleImage(roi_front=(0,62,100,100), roi_back=(152,364,202,149), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_6 = RuleImage(roi_front=(0,52,100,100), roi_back=(360,366,218,150), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_7 = RuleImage(roi_front=(1,43,100,100), roi_back=(583,370,220,144), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_SHEPI_8 = RuleImage(roi_front=(12,36,100,100), roi_back=(815,364,208,152), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_shepi.png")
	# description 
	I_MS_GOODS_FMPI_1 = RuleImage(roi_front=(1,1,100,100), roi_back=(156,66,198,187), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_2 = RuleImage(roi_front=(1,52,100,100), roi_back=(362,71,218,183), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_3 = RuleImage(roi_front=(7,82,100,100), roi_back=(587,83,224,171), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_4 = RuleImage(roi_front=(5,104,100,100), roi_back=(806,81,214,173), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_5 = RuleImage(roi_front=(0,62,100,100), roi_back=(152,364,202,149), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_6 = RuleImage(roi_front=(0,52,100,100), roi_back=(360,366,218,150), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_7 = RuleImage(roi_front=(1,43,100,100), roi_back=(583,370,220,144), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_FMPI_8 = RuleImage(roi_front=(12,36,100,100), roi_back=(815,364,208,152), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_fmpi.png")
	# description 
	I_MS_GOODS_HEISUI_1 = RuleImage(roi_front=(1,1,100,100), roi_back=(156,66,198,187), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_2 = RuleImage(roi_front=(1,52,100,100), roi_back=(362,71,218,183), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_3 = RuleImage(roi_front=(7,82,100,100), roi_back=(587,83,224,171), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_4 = RuleImage(roi_front=(5,104,100,100), roi_back=(806,81,214,173), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_5 = RuleImage(roi_front=(0,62,100,100), roi_back=(152,364,202,149), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_6 = RuleImage(roi_front=(0,52,100,100), roi_back=(360,366,218,150), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_7 = RuleImage(roi_front=(1,43,100,100), roi_back=(583,370,220,144), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_GOODS_HEISUI_8 = RuleImage(roi_front=(12,36,100,100), roi_back=(815,364,208,152), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_heisui.png")
	# description 
	I_MS_FMPI = RuleImage(roi_front=(432,127,54,79), roi_back=(387,95,161,154), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/ms_fmpi.png")


	# Image Rule Assets
	# description 
	I_MS_PRICE_1 = RuleImage(roi_front=(72,1,172,45), roi_back=(159,252,173,48), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_2 = RuleImage(roi_front=(3,29,100,100), roi_back=(383,250,175,49), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_3 = RuleImage(roi_front=(1,42,100,100), roi_back=(610,251,172,47), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_4 = RuleImage(roi_front=(0,31,100,100), roi_back=(836,253,171,46), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_5 = RuleImage(roi_front=(19,82,100,100), roi_back=(158,513,174,45), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_6 = RuleImage(roi_front=(0,37,100,100), roi_back=(386,512,172,48), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_7 = RuleImage(roi_front=(0,37,100,100), roi_back=(608,511,175,49), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICE_8 = RuleImage(roi_front=(0,58,100,100), roi_back=(833,512,174,46), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_jade.png")
	# description 
	I_MS_PRICES_1 = RuleImage(roi_front=(72,1,172,45), roi_back=(159,252,173,48), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_2 = RuleImage(roi_front=(3,29,100,100), roi_back=(383,250,175,49), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_3 = RuleImage(roi_front=(1,42,100,100), roi_back=(610,251,172,47), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_4 = RuleImage(roi_front=(0,31,100,100), roi_back=(836,253,171,46), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_5 = RuleImage(roi_front=(19,82,100,100), roi_back=(158,513,174,45), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_6 = RuleImage(roi_front=(0,37,100,100), roi_back=(386,512,172,48), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_7 = RuleImage(roi_front=(0,37,100,100), roi_back=(608,511,175,49), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")
	# description 
	I_MS_PRICES_8 = RuleImage(roi_front=(0,58,100,100), roi_back=(833,512,174,46), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mshop/mshop_ms_gold.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_MS_PRICENUM_1 = RuleOcr(roi=(173,253,151,44), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_1")
	# Ocr-description 
	O_MS_PRICENUM_2 = RuleOcr(roi=(398,256,152,37), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_2")
	# Ocr-description 
	O_MS_PRICENUM_3 = RuleOcr(roi=(619,258,155,37), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_3")
	# Ocr-description 
	O_MS_PRICENUM_4 = RuleOcr(roi=(846,255,156,38), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_4")
	# Ocr-description 
	O_MS_PRICENUM_5 = RuleOcr(roi=(169,515,157,43), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_5")
	# Ocr-description 
	O_MS_PRICENUM_6 = RuleOcr(roi=(400,516,147,42), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_6")
	# Ocr-description 
	O_MS_PRICENUM_7 = RuleOcr(roi=(620,516,155,41), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_7")
	# Ocr-description 
	O_MS_PRICENUM_8 = RuleOcr(roi=(843,516,159,41), area=(0,0,100,100), mode="Digit", method="Default", keyword="", name="ms_pricenum_8")


	# Click Rule Assets
	# description 
	C_T_EXIT_SUCCESS = RuleClick(roi_front=(1187,361,63,119), roi_back=(1185,360,66,122), name="t_exit_success")
	# description 
	C_T_EXIT_SIGN = RuleClick(roi_front=(851,95,38,30), roi_back=(850,94,41,33), name="t_exit_sign")
	# description 
	C_T_TONORMAL = RuleClick(roi_front=(1132,137,74,47), roi_back=(1131,135,77,50), name="t_tonormal")


	# Image Rule Assets
	# description 
	I_MIAN_TO_TASK = RuleImage(roi_front=(788,451,22,23), roi_back=(583,303,418,270), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_mian_to_task.png")
	# description 
	I_PAGE_TASK = RuleImage(roi_front=(264,41,187,51), roi_back=(257,23,201,84), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_page_task.png")
	# description 
	I_FINISH = RuleImage(roi_front=(1120,594,88,87), roi_back=(1106,578,117,116), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_finish.png")
	# description 
	I_T_BACK_RED_SIGN = RuleImage(roi_front=(850,91,45,37), roi_back=(811,63,117,94), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/t_back_red_sign.png")
	# description 
	I_SUCCESS = RuleImage(roi_front=(307,27,176,54), roi_back=(300,13,193,90), threshold=0.7, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_success.png")
	# description 
	I_TASK_TO_MAIN = RuleImage(roi_front=(17,11,46,54), roi_back=(0,0,92,98), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_task_to_main.png")
	# description 
	I_NORMAL = RuleImage(roi_front=(1130,123,88,77), roi_back=(1099,91,149,132), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_normal.png")
	# description 
	I_CORD_EXIT = RuleImage(roi_front=(1163,38,63,27), roi_back=(1111,15,158,131), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/cord_exit.png")
	# description 
	I_CORD_BACK_RED = RuleImage(roi_front=(1159,42,45,43), roi_back=(1128,19,110,97), threshold=0.6, method="Template matching", file="./tasks/DailyForFlag/tingyuan/cord_back_red.png")
	# description 
	I_T_SIGN_FLAG = RuleImage(roi_front=(869,452,63,34), roi_back=(803,387,203,275), threshold=0.7, method="Template matching", file="./tasks/DailyForFlag/tingyuan/t_sign_flag.png")
	# description 
	I_T_SPECIAL_FLAG = RuleImage(roi_front=(1140,629,47,67), roi_back=(1092,568,138,143), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/t_special_flag.png")


	# Click Rule Assets
	# description 
	C_FRIEND_HELP_CLICK = RuleClick(roi_front=(1204,540,38,70), roi_back=(1203,539,41,73), name="friend_help_click")


	# Image Rule Assets
	# description 
	I_INVITE = RuleImage(roi_front=(1094,619,89,77), roi_back=(1088,602,97,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_invite.png")
	# description 
	I_FORM = RuleImage(roi_front=(530,482,61,42), roi_back=(469,470,324,72), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_form.png")
	# description 
	I_FORM_OVER = RuleImage(roi_front=(736,25,51,54), roi_back=(716,10,83,81), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_form_over.png")
	# description 
	I_SELECT_LEVEL = RuleImage(roi_front=(965,641,66,54), roi_back=(953,626,86,84), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_select_level.png")
	# description 
	I_CREATE_TEAM = RuleImage(roi_front=(1010,603,135,45), roi_back=(981,593,182,68), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_create_team.png")
	# description 
	I_CREATE_AGAIN = RuleImage(roi_front=(832,564,94,49), roi_back=(815,556,124,69), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_create_again.png")
	# description 
	I_LIST_MEMBER = RuleImage(roi_front=(77,199,44,124), roi_back=(65,188,70,142), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_list_member.png")
	# description 
	I_TO_AP = RuleImage(roi_front=(926,265,46,45), roi_back=(924,263,54,52), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_to_ap.png")
	# description 
	I_SAVE_ALL = RuleImage(roi_front=(1199,497,37,83), roi_back=(1175,481,83,123), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_save_all.png")
	# description 
	I_ENSURE_AP = RuleImage(roi_front=(707,408,100,44), roi_back=(670,397,174,69), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_ensure_ap.png")
	# description 
	I_BACK_YELLOW = RuleImage(roi_front=(28,19,47,44), roi_back=(16,8,71,71), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_back_yellow.png")
	# description 
	I_BACK_BLACK = RuleImage(roi_front=(24,17,54,49), roi_back=(7,0,85,82), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_back_black.png")
	# description 
	I_TO_TEAM = RuleImage(roi_front=(65,600,62,74), roi_back=(21,572,113,112), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_to_team.png")
	# description 
	I_BATTLE = RuleImage(roi_front=(1179,603,78,72), roi_back=(1162,580,114,126), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_battle.png")
	# description 
	I_ENSURE_EXIT = RuleImage(roi_front=(708,404,117,54), roi_back=(651,375,199,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_ensure_exit.png")
	# description 
	I_EXIT_2 = RuleImage(roi_front=(353,568,102,44), roi_back=(332,541,157,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_exit_2.png")
	# description 
	I_UNLOCK = RuleImage(roi_front=(28,647,29,30), roi_back=(1,627,75,78), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_unlock.png")
	# description 
	I_LOCK = RuleImage(roi_front=(25,645,33,30), roi_back=(11,627,63,70), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_lock.png")
	# description 
	I_EXIT3 = RuleImage(roi_front=(722,415,75,33), roi_back=(697,403,131,53), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/exit3.png")
	# description 
	I_FRIEND_HELP = RuleImage(roi_front=(1205,541,38,71), roi_back=(1187,512,71,118), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/friend_help.png")
	# description 
	I_FRIEND_HELP_FLAG = RuleImage(roi_front=(803,107,167,34), roi_back=(782,93,210,63), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/friend_help_flag.png")


	# Click Rule Assets
	# description 
	C_TO_ACCOUNT = RuleClick(roi_front=(21,27,72,63), roi_back=(21,27,72,63), name="to_account")
	# description 
	C_NET_CLICK = RuleClick(roi_front=(191,219,187,296), roi_back=(190,218,190,299), name="net_click")


	# Image Rule Assets
	# description 
	I_PAGE_ACCOUNT = RuleImage(roi_front=(222,489,54,54), roi_back=(169,394,156,190), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_page_account.png")
	# description 
	I_REAL_FLAG_1 = RuleImage(roi_front=(458,293,29,31), roi_back=(143,129,65,240), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")
	# description 
	I_REAL_FLAG_2 = RuleImage(roi_front=(457,292,32,34), roi_back=(443,128,67,200), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")
	# description 
	I_REAL_FLAG_3 = RuleImage(roi_front=(455,291,35,37), roi_back=(741,129,68,240), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")
	# description 
	I_NET_CHECK = RuleImage(roi_front=(121,130,334,487), roi_back=(119,129,336,489), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/net_check.png")
	# description 
	I_NET_NORMAL_FLAG = RuleImage(roi_front=(1020,328,27,31), roi_back=(129,110,1022,507), threshold=0.7, method="Template matching", file="./tasks/DailyForFlag/xiezuo/net_normal_flag.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_ACC_NAME = RuleOcr(roi=(233,283,226,46), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="acc_name")
	# description 
	O_HUAHE = RuleOcr(roi=(477,634,300,71), area=(493,665,259,31), mode="Single", method="Default", keyword="", name="huahe")


