from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DailyForFlagAssets: 


	# Click Rule Assets
	# description 
	C_BACK_RED = RuleClick(roi_front=(838,134,57,49), roi_back=(837,133,60,50), name="back_red")


	# Image Rule Assets
	# description 
	I_QIYUAN = RuleImage(roi_front=(966,630,67,61), roi_back=(949,607,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_qiyuan.png")
	# description 
	I_BTN_THINK = RuleImage(roi_front=(928,613,38,35), roi_back=(916,596,70,70), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_btn_think.png")
	# description 
	I_H_BACK_RED = RuleImage(roi_front=(851,144,31,33), roi_back=(777,114,182,110), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_h_back_red.png")
	# description 
	I_BTN_ENSURE = RuleImage(roi_front=(693,405,134,49), roi_back=(639,376,244,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_btn_ensure.png")
	# description 
	I_TO_THINK = RuleImage(roi_front=(1060,602,58,53), roi_back=(1042,580,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_to_think.png")
	# description 
	I_FLAG_THINK = RuleImage(roi_front=(969,176,64,106), roi_back=(938,147,133,158), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_flag_think.png")
	# description 
	I_H_BACK_RED2 = RuleImage(roi_front=(933,88,44,39), roi_back=(906,55,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/huili/huili_h_back_red2.png")


	# Image Rule Assets
	# description 
	I_DONATE = RuleImage(roi_front=(270,494,27,26), roi_back=(243,465,80,87), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_donate.png")
	# description 
	I_ADD = RuleImage(roi_front=(780,276,60,55), roi_back=(763,251,100,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_add.png")
	# description 
	I_LIMIT = RuleImage(roi_front=(826,349,47,77), roi_back=(817,342,69,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_limit.png")
	# description 
	I_CLICK_DONATE = RuleImage(roi_front=(577,524,133,48), roi_back=(553,501,178,92), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_click_donate.png")
	# description 
	I_AWARD = RuleImage(roi_front=(476,178,327,100), roi_back=(438,160,399,133), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/juangou/juangou_award.png")


	# Image Rule Assets
	# 邮件 
	I_M_MAIN_TO_MAIL = RuleImage(roi_front=(1135,31,41,31), roi_back=(1114,3,82,89), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_main_to_mail.png")
	# 领取邮件 
	I_M_GET_MAIL = RuleImage(roi_front=(65,575,87,66), roi_back=(61,563,98,92), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_get_mail.png")
	# description 
	I_M_PAGE_GET = RuleImage(roi_front=(554,48,195,51), roi_back=(539,33,225,88), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_page_get.png")
	# description 
	I_M_ENSURE_GET = RuleImage(roi_front=(728,549,96,46), roi_back=(676,531,188,88), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_ensure_get.png")
	# 奖励 
	I_M_AWARD = RuleImage(roi_front=(478,131,325,100), roi_back=(427,125,416,114), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_award.png")
	# description 
	I_M_BACK_RED = RuleImage(roi_front=(1152,91,49,47), roi_back=(1148,84,57,61), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_back_red.png")
	# description 
	I_M_PAGE_MAIL = RuleImage(roi_front=(609,54,70,47), roi_back=(585,38,115,89), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/mail/mail_m_page_mail.png")


	# Image Rule Assets
	# description 
	I_MIAN_TO_TASK = RuleImage(roi_front=(788,451,22,23), roi_back=(583,303,418,270), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_mian_to_task.png")
	# description 
	I_PAGE_TASK = RuleImage(roi_front=(264,41,187,51), roi_back=(257,23,201,84), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_page_task.png")
	# description 
	I_FINISH = RuleImage(roi_front=(1120,594,88,87), roi_back=(1106,578,117,116), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_finish.png")
	# description 
	I_T_BACK_RED = RuleImage(roi_front=(850,91,45,37), roi_back=(844,80,59,55), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_t_back_red.png")
	# description 
	I_SUCCESS = RuleImage(roi_front=(307,27,176,54), roi_back=(300,13,193,90), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_success.png")
	# description 
	I_TASK_TO_MAIN = RuleImage(roi_front=(17,11,46,54), roi_back=(0,0,92,98), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_task_to_main.png")
	# description 
	I_NORMAL = RuleImage(roi_front=(1130,123,88,77), roi_back=(1099,91,149,132), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tingyuan/tingyuan_normal.png")


	# Image Rule Assets
	# description 
	I_INVITE = RuleImage(roi_front=(1094,619,89,77), roi_back=(1088,602,97,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_invite.png")
	# description 
	I_FORM = RuleImage(roi_front=(530,482,61,42), roi_back=(469,470,324,72), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_form.png")
	# description 
	I_FORM_OVER = RuleImage(roi_front=(736,25,51,54), roi_back=(716,10,83,81), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_form_over.png")
	# description 
	I_SELECT_LEVEL = RuleImage(roi_front=(965,641,66,54), roi_back=(953,626,86,84), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_select_level.png")
	# description 
	I_CREATE_TEAM = RuleImage(roi_front=(1010,603,135,45), roi_back=(981,593,182,68), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_create_team.png")
	# description 
	I_CREATE_AGAIN = RuleImage(roi_front=(832,564,94,49), roi_back=(815,556,124,69), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_create_again.png")
	# description 
	I_LIST_MEMBER = RuleImage(roi_front=(77,199,44,124), roi_back=(65,188,70,142), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_list_member.png")
	# description 
	I_TO_AP = RuleImage(roi_front=(926,265,46,45), roi_back=(924,263,54,52), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_to_ap.png")
	# description 
	I_SAVE_ALL = RuleImage(roi_front=(1199,497,37,83), roi_back=(1175,481,83,123), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_save_all.png")
	# description 
	I_ENSURE_AP = RuleImage(roi_front=(707,408,100,44), roi_back=(670,397,174,69), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_ensure_ap.png")
	# description 
	I_BACK_YELLOW = RuleImage(roi_front=(28,19,47,44), roi_back=(16,8,71,71), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_back_yellow.png")
	# description 
	I_BACK_BLACK = RuleImage(roi_front=(24,17,54,49), roi_back=(7,0,85,82), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_back_black.png")
	# description 
	I_TO_TEAM = RuleImage(roi_front=(65,600,62,74), roi_back=(21,572,113,112), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_to_team.png")
	# description 
	I_BATTLE = RuleImage(roi_front=(1179,603,78,72), roi_back=(1162,580,114,126), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_battle.png")
	# description 
	I_ENSURE_EXIT = RuleImage(roi_front=(708,404,117,54), roi_back=(651,375,199,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_ensure_exit.png")
	# description 
	I_EXIT_2 = RuleImage(roi_front=(353,568,102,44), roi_back=(332,541,157,100), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_exit_2.png")
	# description 
	I_UNLOCK = RuleImage(roi_front=(28,647,29,30), roi_back=(1,627,75,78), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_unlock.png")
	# description 
	I_LOCK = RuleImage(roi_front=(25,645,33,30), roi_back=(11,627,63,70), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/tongxin/tongxin_lock.png")


	# Click Rule Assets
	# description 
	C_TO_ACCOUNT = RuleClick(roi_front=(21,27,72,63), roi_back=(21,27,72,63), name="to_account")


	# Image Rule Assets
	# description 
	I_PAGE_ACCOUNT = RuleImage(roi_front=(222,489,54,54), roi_back=(169,394,156,190), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_page_account.png")
	# description 
	I_REAL_FLAG_1 = RuleImage(roi_front=(458,293,29,31), roi_back=(143,129,65,240), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")
	# description 
	I_REAL_FLAG_2 = RuleImage(roi_front=(457,292,32,34), roi_back=(443,128,67,200), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")
	# description 
	I_REAL_FLAG_3 = RuleImage(roi_front=(455,291,35,37), roi_back=(741,129,68,240), threshold=0.8, method="Template matching", file="./tasks/DailyForFlag/xiezuo/xiezuo_real_flag_1.png")


	# Ocr Rule Assets
	# Ocr-description 
	O_ACC_NAME = RuleOcr(roi=(233,283,226,46), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="acc_name")


