from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class PlotlineAssets: 


	# Click Rule Assets
	# description 
	C_CLICK_CURSOR = RuleClick(roi_front=(0,0,20,20), roi_back=(0,0,20,20), name="click_cursor")
	# description 
	C_CLICK_LEASE = RuleClick(roi_front=(296,417,55,95), roi_back=(294,415,58,98), name="click_lease")
	# description 
	C_CLICK_CHANGE = RuleClick(roi_front=(308,452,75,75), roi_back=(306,451,78,78), name="click_change")
	# description 
	C_CLICK_RANDOM_1 = RuleClick(roi_front=(1013,645,29,42), roi_back=(1012,644,31,45), name="click_random_1")
	# description 
	C_CLICK_RANDOM_2 = RuleClick(roi_front=(1110,641,27,47), roi_back=(1109,640,30,50), name="click_random_2")
	# description 
	C_CLICK_RANDOM_3 = RuleClick(roi_front=(1203,642,27,46), roi_back=(1202,641,30,49), name="click_random_3")
	# description 
	C_CLICK_TIMEOUT = RuleClick(roi_front=(957,573,15,19), roi_back=(956,572,18,22), name="click_timeout")
	# description 
	C_CLICK_FIND_FLAG = RuleClick(roi_front=(51,545,76,56), roi_back=(50,544,79,59), name="click_find_flag")


	# Image Rule Assets
	# description 
	I_CLICK_DIALOGUE_1 = RuleImage(roi_front=(651,165,26,18), roi_back=(0,0,1280,720), threshold=0.85, method="Template matching", file="./tasks/Plotline/res/click_dialogue_1.png")
	# description 
	I_CLICK_JUMP = RuleImage(roi_front=(846,559,51,29), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/click_jump.png")
	# description 
	I_PAGE_CLICK_ANY = RuleImage(roi_front=(540,508,213,27), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/page_click_any.png")
	# description 
	I_CLICK_CURSOR = RuleImage(roi_front=(640,617,23,31), roi_back=(0,0,1280,720), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_cursor.png")
	# description 
	I_PAGE_SUMMON = RuleImage(roi_front=(381,91,89,92), roi_back=(255,66,834,556), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/page_summon.png")
	# description 
	I_CLICK_SUMMON = RuleImage(roi_front=(454,629,103,35), roi_back=(269,575,731,135), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_summon.png")
	# description 
	I_CLICK_ATTACK = RuleImage(roi_front=(620,200,16,21), roi_back=(0,0,1280,720), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_attack.png")
	# description 
	I_CLICK_EYE = RuleImage(roi_front=(596,126,83,63), roi_back=(0,0,1280,720), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_eye.png")
	# description 
	I_CLICK_DIALOGUE_2 = RuleImage(roi_front=(603,274,18,33), roi_back=(0,0,1280,720), threshold=0.85, method="Template matching", file="./tasks/Plotline/res/click_dialogue_2.png")
	# description 
	I_CLICK_SPEED_X2 = RuleImage(roi_front=(1143,39,50,39), roi_back=(925,13,325,111), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_speed_x2.png")
	# description 
	I_CLICK_SPEED_X1 = RuleImage(roi_front=(1146,34,45,49), roi_back=(997,11,257,128), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_speed_x1.png")
	# description 
	I_CLICK_TO_AUTO = RuleImage(roi_front=(37,646,27,31), roi_back=(9,620,100,81), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_to_auto.png")
	# description 
	I_CLICK_BATTLE_SPEED_X1 = RuleImage(roi_front=(114,605,26,23), roi_back=(99,589,62,57), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_battle_speed_x1.png")
	# description 
	I_CLICK_AUTO = RuleImage(roi_front=(37,646,27,31), roi_back=(9,620,100,81), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_auto.png")
	# description 
	I_CLICK_REFUSE = RuleImage(roi_front=(367,588,211,43), roi_back=(227,518,419,154), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_refuse.png")
	# description 
	I_CLICK_BACK_RED = RuleImage(roi_front=(1149,75,43,43), roi_back=(771,10,496,320), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_back_red.png")
	# description 
	I_CLICK_LV = RuleImage(roi_front=(854,244,25,22), roi_back=(704,134,387,374), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_lv.png")
	# description 
	I_CLICK_TO_EXPLORATION = RuleImage(roi_front=(609,460,61,35), roi_back=(449,370,232,172), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_to_exploration.png")
	# description 
	I_PAGE_MAIN = RuleImage(roi_front=(370,37,19,39), roi_back=(18,19,507,94), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/page_main.png")
	# description 
	I_CLICK_TO_PRIVILEGES = RuleImage(roi_front=(248,325,37,41), roi_back=(82,166,495,349), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_to_privileges.png")
	# description 
	I_PAGE_PRIVILEGES = RuleImage(roi_front=(92,17,159,43), roi_back=(18,5,363,92), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/page_privileges.png")
	# description 
	I_CLICK_PRIVILEGES_SUBPAGE = RuleImage(roi_front=(50,332,108,43), roi_back=(11,108,181,391), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/click_privileges_subpage.png")
	# description 
	I_SUBPAGE_PRIVILEGES = RuleImage(roi_front=(241,189,62,73), roi_back=(195,75,326,599), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/subpage_privileges.png")
	# description 
	I_FLAG_LEASE = RuleImage(roi_front=(338,248,67,18), roi_back=(320,181,298,92), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/flag_lease.png")
	# description 
	I_FLAG_HELP = RuleImage(roi_front=(743,379,22,23), roi_back=(0,0,1280,720), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/flag_help.png")
	# description 
	I_FLAG_CHANGE = RuleImage(roi_front=(42,646,57,33), roi_back=(11,449,174,253), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/flag_change.png")
	# description 
	I_CLICK_SKILL = RuleImage(roi_front=(1057,656,17,23), roi_back=(834,591,441,120), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_skill.png")
	# description 
	I_CLICK_CV = RuleImage(roi_front=(264,116,29,17), roi_back=(0,0,1280,720), threshold=0.80, method="Template matching", file="./tasks/Plotline/res/click_cv.png")
	# description 
	I_CLICK_EYE_2 = RuleImage(roi_front=(599,108,87,35), roi_back=(0,0,1278,720), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/click_eye_2.png")
	# description 
	I_PAGE_SUMMON_2 = RuleImage(roi_front=(645,571,180,35), roi_back=(321,519,666,187), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/page_summon_2.png")
	# description 
	I_PAGE_PRIVILEGES_2 = RuleImage(roi_front=(951,337,31,32), roi_back=(919,288,79,112), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/page_privileges_2.png")
	# description 
	I_CLICK_PRIVILEGES_SUBPAGE_2 = RuleImage(roi_front=(58,353,92,30), roi_back=(19,115,193,468), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_privileges_subpage_2.png")
	# description 
	I_PAGE_SKIP = RuleImage(roi_front=(729,468,127,42), roi_back=(685,446,231,98), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/page_skip.png")
	# description 
	I_CHECK_UNTICK = RuleImage(roi_front=(425,402,27,34), roi_back=(344,374,196,77), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/check_untick.png")
	# description 
	I_CHECK_TICK = RuleImage(roi_front=(425,402,27,34), roi_back=(344,374,196,77), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/check_tick.png")
	# description 
	I_PAGE_CLICK_ANY2 = RuleImage(roi_front=(162,415,34,37), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/page_click_any2.png")
	# description 
	I_PAGE_EXP_BATTLE = RuleImage(roi_front=(1127,103,47,62), roi_back=(1056,61,180,164), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/page_exp_battle.png")
	# description 
	I_FLAG_HELP2 = RuleImage(roi_front=(607,539,29,30), roi_back=(135,484,972,216), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/flag_help2.png")
	# description 
	I_FLAG_ON_FIELD = RuleImage(roi_front=(650,515,26,23), roi_back=(628,488,79,154), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/flag_on_field.png")
	# description 
	I_CLICK_BATTLE = RuleImage(roi_front=(599,108,87,35), roi_back=(0,0,1280,720), threshold=0.7, method="Template matching", file="./tasks/Plotline/res/click_battle.png")
	# description 
	I_CLICK_JUMP2 = RuleImage(roi_front=(720,446,120,33), roi_back=(637,407,277,110), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/click_jump2.png")
	# Plotline 新庭院 main 页面检测资源 
	I_PLOTLINE_NEW_MAIN_CHECK = RuleImage(roi_front=(805,107,103,50), roi_back=(718,67,312,143), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/plotline_new_main_check.png")
	# Plotline 新庭院进入探索入口资源 
	I_PLOTLINE_NEW_MAIN_GOTO_EXPLORATION = RuleImage(roi_front=(656,142,37,63), roi_back=(305,106,725,211), threshold=0.8, method="Template matching", file="./tasks/Plotline/res/plotline_new_main_goto_exploration.png")


	# Ocr Rule Assets
	# description 
	O_CHARACTER_LEVEL = RuleOcr(roi=(13,25,23,23), area=(0,0,100,100), mode="DIGIT", method="Default", keyword="", name="character_level")


	# Swipe Rule Assets
	# description 
	S_SWIPE_SUMMON = RuleSwipe(roi_front=(494,158,326,71), roi_back=(484,422,333,89), mode="default", name="swipe_summon")
	# description 
	S_SWIPE_SHIKIGAMI = RuleSwipe(roi_front=(302,589,39,62), roi_back=(623,306,42,107), mode="default", name="swipe_shikigami")
	# description 
	S_SWIPE_BATTLE = RuleSwipe(roi_front=(547,6,38,7), roi_back=(638,7,42,7), mode="default", name="swipe_battle")
	# description 
	S_SWIPE_BATTLE2 = RuleSwipe(roi_front=(1065,532,38,9), roi_back=(1137,531,45,9), mode="default", name="swipe_battle2")
	# description 
	S_SWIPE_FIND_FLAG = RuleSwipe(roi_front=(1067,618,141,47), roi_back=(104,616,178,52), mode="default", name="swipe_find_flag")


