from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EvoZoneAssets: 


	# Image Rule Assets
	# 火麒麟进入 
	I_FIRE_KIRIN = RuleImage(roi_front=(114,128,183,328), roi_back=(66,68,280,484), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/fire_kirin.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(965,607,89,47), roi_back=(923,560,169,142), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/form_team.png")
	# description 
	I_EVOZONE_LOCK = RuleImage(roi_front=(700,653,29,34), roi_back=(642,627,169,92), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/evozone_lock.png")
	# description 
	I_EVOZONE_UNLOCK = RuleImage(roi_front=(701,652,25,35), roi_back=(656,635,211,80), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/evozone_unlock.png")
	# 点击挑战 
	I_EVOZONE_FIRE = RuleImage(roi_front=(1149,602,81,34), roi_back=(1093,537,178,162), threshold=0.6, method="Template matching", file="./tasks/EvoZone/o/evozone_fire.png")
	# 式神录 
	I_SHI_RECORDS = RuleImage(roi_front=(844,570,39,40), roi_back=(811,531,104,109), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/shi_records.png")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/o_pet_present.png")
	# 风麒麟进入 
	I_WIND_KIRIN = RuleImage(roi_front=(424,97,190,273), roi_back=(395,58,247,520), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/wind_kirin.png")
	# 水麒麟进入 
	I_WATER_KIRIN = RuleImage(roi_front=(734,130,183,299), roi_back=(689,62,273,511), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/water_kirin.png")
	# 雷麒麟进入 
	I_LIGHTNING_KIRIN = RuleImage(roi_front=(1037,120,180,237), roi_back=(1002,87,245,461), threshold=0.8, method="Template matching", file="./tasks/EvoZone/o/lightning_kirin.png")


	# List Rule Assets
	# 这个是觉醒界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/EvoZone/res", direction="vertical", mode="ocr", roi_back=(129,104,79,574), size=(31, 103), 
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(0,0,100,100), mode="Full", method="Default", keyword="", name="o_test_ocr")


