from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeRealmAssets: 


	# Click Rule Assets
	# 鬼灵咒符进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_1_GROWN = RuleClick(roi_front=(626,296,26,74), roi_back=(626,296,26,74), name="realm_1_grown")
	# 鬼灵咒符进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_1_CARD = RuleClick(roi_front=(930,290,24,70), roi_back=(930,290,24,70), name="realm_1_card")


	# Image Rule Assets
	# 鬼灵咒符结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_1_PAGE = RuleImage(roi_front=(731,103,54,64), roi_back=(668,57,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm1/realm1_realm_1_page.png")


	# Click Rule Assets
	# 狐梦之乡进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_2_GROWN = RuleClick(roi_front=(663,328,26,74), roi_back=(663,328,26,74), name="realm_2_grown")
	# 狐梦之乡进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_2_CARD = RuleClick(roi_front=(945,334,21,79), roi_back=(945,334,21,79), name="realm_2_card")


	# Image Rule Assets
	# 狐梦之乡结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_2_PAGE = RuleImage(roi_front=(252,191,89,44), roi_back=(223,140,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm2/realm2_realm_2_page.png")


