from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeRealmAssets: 


	# Click Rule Assets
	# 鬼灵咒符进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_1_GROWN = RuleClick(roi_front=(626,296,26,74), roi_back=(626,296,26,74), name="realm_1_grown")
	# 鬼灵咒符进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_1_CARD = RuleClick(roi_front=(930,290,24,70), roi_back=(930,290,24,70), name="realm_1_card")


	# Image Rule Assets
	# 鬼灵咒符结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_1_PAGE = RuleImage(roi_front=(731,103,54,64), roi_back=(668,57,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm1/realm1_realm_1_page.png")


	# Click Rule Assets
	# 狐梦之乡进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_2_GROWN = RuleClick(roi_front=(663,328,26,74), roi_back=(663,328,26,74), name="realm_2_grown")
	# 狐梦之乡进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_2_CARD = RuleClick(roi_front=(945,334,21,79), roi_back=(945,334,21,79), name="realm_2_card")


	# Image Rule Assets
	# 狐梦之乡结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_2_PAGE = RuleImage(roi_front=(252,191,89,44), roi_back=(223,140,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm2/realm2_realm_2_page.png")


	# Click Rule Assets
	# 编心织忆进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_3_GROWN = RuleClick(roi_front=(610,305,24,53), roi_back=(610,305,24,53), name="realm_3_grown")
	# 编心织忆进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_3_CARD = RuleClick(roi_front=(945,306,20,53), roi_back=(945,306,20,53), name="realm_3_card")


	# Image Rule Assets
	# 编心织忆结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_3_PAGE = RuleImage(roi_front=(803,102,99,60), roi_back=(785,58,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm3/realm3_realm_3_page.png")


	# Click Rule Assets
	# 花海繁生进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_4_GROWN = RuleClick(roi_front=(610,321,24,53), roi_back=(610,321,24,53), name="realm_4_grown")
	# 花海繁生进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_4_CARD = RuleClick(roi_front=(937,320,24,53), roi_back=(937,320,24,53), name="realm_4_card")


	# Image Rule Assets
	# 花海繁生结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_4_PAGE = RuleImage(roi_front=(130,271,66,67), roi_back=(78,234,146,139), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm4/realm4_realm_4_page.png")


	# Click Rule Assets
	# 莲心梦乡进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_5_GROWN = RuleClick(roi_front=(649,351,24,53), roi_back=(649,351,24,53), name="realm_5_grown")
	# 莲心梦乡进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_5_CARD = RuleClick(roi_front=(933,354,24,53), roi_back=(933,354,24,53), name="realm_5_card")


	# Image Rule Assets
	# 莲心梦乡结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_5_PAGE = RuleImage(roi_front=(583,122,151,55), roi_back=(504,92,320,145), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm5/realm5_realm_5_page.png")


	# Click Rule Assets
	# 歌弈花坊进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_6_GROWN = RuleClick(roi_front=(610,410,24,53), roi_back=(610,410,24,53), name="realm_6_grown")
	# 歌弈花坊进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_6_CARD = RuleClick(roi_front=(837,401,24,53), roi_back=(837,401,24,53), name="realm_6_card")


	# Image Rule Assets
	# 歌弈花坊结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_6_PAGE = RuleImage(roi_front=(170,301,145,84), roi_back=(91,228,333,196), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm6/realm6_realm_6_page.png")


	# Click Rule Assets
	# 斗鱼之地进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_7_GROWN = RuleClick(roi_front=(639,319,24,53), roi_back=(639,319,24,53), name="realm_7_grown")
	# 斗鱼之地进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_7_CARD = RuleClick(roi_front=(936,321,24,53), roi_back=(936,321,24,53), name="realm_7_card")


	# Image Rule Assets
	# 斗鱼之地结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_7_PAGE = RuleImage(roi_front=(1148,546,116,113), roi_back=(1109,504,171,177), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm7/realm7_realm_7_page.png")


	# Click Rule Assets
	# 金鱼梦境进式神育成的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_8_GROWN = RuleClick(roi_front=(628,276,24,53), roi_back=(628,276,24,53), name="realm_8_grown")
	# 金鱼梦境进结界卡的点击区域（起点抄默认套，按实际截图调） 
	C_REALM_8_CARD = RuleClick(roi_front=(978,281,24,53), roi_back=(978,281,24,53), name="realm_8_card")


	# Image Rule Assets
	# 金鱼梦境结界页判据（起点抄默认套，按实际截图调） 
	I_REALM_8_PAGE = RuleImage(roi_front=(281,114,79,57), roi_back=(248,80,137,100), threshold=0.7, method="Template matching", file="./tasks/Component/CostumeRealm/realm8/realm8_realm_8_page.png")


