from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MultiAccountSignInAssets: 


	# Image Rule Assets
	# 切换列表 
	I_CHANGE_ITEM = RuleImage(roi_front=(1190,526,40,32), roi_back=(1153,124,119,466), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_change_item.png")
	#  
	I_TO_PAGE_SHI = RuleImage(roi_front=(1191,465,34,32), roi_back=(1165,124,91,447), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_to_page_shi.png")
	# 领取式神主页面 
	I_PAGE_GET_SHI = RuleImage(roi_front=(1095,57,156,34), roi_back=(1062,35,207,94), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_page_get_shi.png")
	# 领取当天的奖励 
	I_GET_SHI = RuleImage(roi_front=(290,443,83,77), roi_back=(232,327,1017,283), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_get_shi.png")
	# 成功领取当日奖励 
	I_GET_SHI_SUCCESS = RuleImage(roi_front=(1049,175,65,61), roi_back=(1027,145,110,125), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_get_shi_success.png")
	# 已经领取的奖励页面 
	I_GET_SHI_OVER = RuleImage(roi_front=(523,538,235,40), roi_back=(478,510,316,89), threshold=0.7, method="Template matching", file="./tasks/MultiAccountSignIn/res/res_get_shi_over.png")


